// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team155.robot.commands;
import org.usfirst.frc.team155.robot.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class TankDrive extends Command {
	private double Kp= 1;
	private double stickDifferential;
	private double motorDifferential;
	private double drivePower;
	private double leftStick;
	private double rightStick;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public TankDrive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drivetrain);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    
    
    }
    
    protected void execute() {
    	leftStick = Robot.oi.getLeftStick().getY();
    	rightStick = +Robot.oi.getRightStick().getY();
    	
    	
    	drivePower=(leftStick+rightStick)/2;
    	stickDifferential =rightStick- leftStick;
    	motorDifferential = Kp*(stickDifferential-(Robot.drivetrain.getGyroRate()/360));
    	Robot.drivetrain.tankDrivejoyGyro(drivePower-motorDifferential,drivePower+motorDifferential);
    	
    	
    //	Robot.drivetrain.tankDrivejoy(Robot.oi.getLeftStick(),Robot.oi.getRightStick());
    }
    // Called repeatedly when this Command is scheduled to run
    @Override
   
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
